@startuml
|Penghuni|
start
:Kirim perintah 'Riwayat';
|Sistem|
:Cek history pembayaran;
|Basis Data|
:Data invoice status PAID;
|Sistem|
:Susun daftar riwayat;
|Penghuni|
:Terima list riwayat pembayaran;
stop
@enduml