@startuml
|Penghuni|
start
:Kirim perintah 'Cek Tagihan';
|Sistem|
:Cek tagihan aktif;
|Basis Data|
:Data invoice UNPAID;
|Sistem|
:Proses detail tagihan;
|Penghuni|
:Terima info tagihan terkini;
stop
@enduml