sequenceDiagram
    autonumber
    actor Penghuni
    participant Sistem
    participant Basis Data

    Penghuni->>Sistem: Minta info tagihan aktif
    activate Sistem
    Sistem->>Basis Data: Query invoices (status = unpaid)
    activate Basis Data
    Basis Data-->>Sistem: Detail tagihan
    deactivate Basis Data
    Sistem->>Sistem: Hitung total tagihan
    Sistem-->>Penghuni: Kirim rincian tagihan & batas waktu
    deactivate Sistem