@startuml
|Penghuni|
start
:Kirim perintah 'Komplain';
:Input detail komplain;
|Sistem|
:Validasi input;
|Basis Data|
:Simpan record komplain baru;
|Sistem|
:Beri feedback diterima;
|Penghuni|
:Terima nomor komplain;
stop
@enduml