@startuml
|Staf/Owner|
start
:Pilih rentang laporan;
|Sistem|
:Filter data transaksi;
|Basis Data|
:Tarik data tagihan;
|Sistem|
:Kalkulasi total & buat laporan;
|Staf/Owner|
:Tampilkan laporan;
stop
@enduml