sequenceDiagram
    autonumber
    actor Pengelola as Staf/Owner
    participant Sistem
    participant Basis Data

    Pengelola->>Sistem: Buka modul komplain
    activate Sistem
    Sistem->>Basis Data: Ambil daftar komplain
    activate Basis Data
    Basis Data-->>Sistem: Data komplain
    deactivate Basis Data
    Sistem-->>Pengelola: List daftar komplain
    deactivate Sistem
    
    opt Jika Staf (Resolusi)
        Pengelola->>Sistem: Update status selesai
        activate Sistem
        Sistem->>Basis Data: Simpan penangan
        activate Basis Data
        Basis Data-->>Sistem: Terupdate
        deactivate Basis Data
        Sistem-->>Pengelola: Berhasil
        deactivate Sistem
    end