@startuml
|Penghuni|
start
:Pilih bayar tagihan;

|Sistem|
:Ambil data tagihan;

if (Tagihan ditemukan?) then (ya)

  if (Status belum dibayar?) then (ya)
    :Kirim permintaan ke payment gateway;

    |Payment Gateway|
    :Proses pembayaran;

    if (Sukses?) then (ya)
      |Sistem|
      :Ubah status tagihan = lunas;
      :Buat notifikasi sukses;
      :Kirim ke chatbot;

    else (gagal)
      |Sistem|
      :Buat notifikasi gagal;
    endif

  else (sudah lunas)
    :Tolak pembayaran;
  endif

else (tidak ditemukan)
  :Kesalahan tagihan;
endif

stop
@enduml