@startuml
|Staff / Owner|
start
:Minta laporan;

|Sistem|
:Verifikasi akun;

if (Valid?) then (ya)

  :Input filter (tanggal/status);

  :Ambil data tagihan;

  if (Data ada?) then (ya)
    :Buat laporan;
    :Tampilkan hasil;
  else (tidak)
    :Tampilkan kosong;
  endif

else (tidak valid)
  :Tolak akses;
endif

stop
@enduml