sequenceDiagram
    autonumber
    actor Pengelola as Staff/Owner
    participant Sistem
    participant Basis Data

    Pengelola->>Sistem: Minta daftar komplain
    Sistem->>Sistem: Verifikasi akun

    alt valid
        Sistem->>Basis Data: Ambil data komplain
        Basis Data-->>Sistem: Data komplain
        Sistem-->>Pengelola: Tampilkan daftar komplain
        opt Jika Staff (Ubah status)
            Pengelola->>Sistem: Ubah status komplain
            Sistem->>Basis Data: Ubah status di Basis Data
            Basis Data-->>Sistem: Oke
            Sistem-->>Pengelola: Notifikasi sukses
        end
    else tidak valid
        Sistem-->>Pengelola: Kesalahan buka halaman
    end
