sequenceDiagram
    autonumber
    actor Pengelola as Staff/Owner
    participant Sistem
    participant Basis Data

    Pengelola->>Sistem: Minta laporan
    Sistem->>Sistem: Verifikasi akun

    alt valid
        Sistem->>Basis Data: Ambil data tagihan
        Basis Data-->>Sistem: Data
        Sistem-->>Pengelola: Laporan
    else tidak valid
        Sistem-->>Pengelola: Kesalahan
    end