sequenceDiagram
    autonumber
    actor Admin
    participant Sistem
    participant Basis Data

    Admin->>Sistem: Minta kelola akun
    Sistem->>Sistem: Verifikasi akun

    alt validasi lolos
        Admin->>Sistem: Kelola data pengguna (tambah/ubah/hapus)
        Sistem->>Basis Data: Ambil/Simpan data
        Basis Data-->>Sistem: Oke
        Sistem-->>Admin: Sukses
    else gagal
        Sistem-->>Admin: Akses ditolak
    end