sequenceDiagram
    autonumber
    actor Staff
    participant Sistem
    participant Basis Data

    Staff->>Sistem: Kelola kamar
    Sistem->>Sistem: Verifikasi akun

    alt valid
        Staff->>Sistem: Tambah/Ubah/Hapus kamar
        Sistem->>Basis Data: Perbarui kamar
        Basis Data-->>Sistem: Oke
        Sistem-->>Staff: Sukses
    else tidak valid
        Sistem-->>Staff: Kesalahan
    end