name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: ./.github/actions/setup-bun
      - run: bun run check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: ./.github/actions/setup-bun
      - run: bun run test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: ./.github/actions/setup-bun
      - run: bun run format:check

  docker-build-push:
    needs: [check, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_REGISTRY: ghcr.io
      BASE_IMAGE_TAG: ghcr.io/${{ github.repository_owner }}

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Create empty .env
        run: touch .env

      - name: Build Images
        run: docker compose build

      - name: Log into registry ${{ env.IMAGE_REGISTRY }}
        if: github.event_name == 'push'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Images to GHCR
        if: github.event_name == 'push'
        run: docker compose push
