name: check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: ./.github/actions/setup-bun
      - run: bun run check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: ./.github/actions/setup-bun
      - run: bun run test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: ./.github/actions/setup-bun
      - run: bun run format:check
